services:
  APP:
    image: flaskapp:1.0
    container_name: app_flask
    command: sh -c 'cd project && python3 proyect.py'
    ports:
      - 5000:5000
    volumes:
      - ./app/proyect.py:/project/proyect.py
